/**
 * 构建时模板内嵌脚本
 *
 * 读取 src/modules/ssr/templates/ 下的 .hbs 模板文件，
 * 生成 src/modules/ssr/templates.ts 将模板内嵌为 TypeScript 字符串常量。
 *
 * 这样模板在编译时就被打包到 JS 产物中，运行时无需 readFileSync，
 * 消除了对 nest-cli.json assets 配置的依赖，构建稳定性更高。
 *
 * 用法：ts-node scripts/build-templates.ts
 * （通过 pnpm prebuild 自动执行）
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';

const PROJECT_ROOT = join(__dirname, '..');
const TEMPLATES_DIR = join(PROJECT_ROOT, 'src', 'modules', 'ssr', 'templates');
const OUTPUT_FILE = join(PROJECT_ROOT, 'src', 'modules', 'ssr', 'templates.ts');

/** 模板文件列表（不含 .hbs 后缀的键名将作为导出变量名的基础） */
const TEMPLATE_FILES = ['article.hbs', 'case.hbs'] as const;

function main(): void {
  const entries: { name: string; varName: string; content: string }[] = [];

  for (const file of TEMPLATE_FILES) {
    const path = join(TEMPLATES_DIR, file);
    const content = readFileSync(path, 'utf-8');
    const name = file.replace(/\.hbs$/, '');
    const varName = name
      .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
      .replace(/^(.)/, (c) => c.toUpperCase()) + 'Template';
    entries.push({ name, varName, content });
  }

  const code = `// Auto-generated by scripts/build-templates.ts — do not edit
// 模板源文件：src/modules/ssr/templates/*.hbs
// 运行 \`pnpm build\` 或直接执行 \`npx ts-node scripts/build-templates.ts\` 重新生成

${entries.map((e) => `export const ${e.varName} = ${JSON.stringify(e.content)};`).join('\n\n')}
`;

  writeFileSync(OUTPUT_FILE, code, 'utf-8');
  console.log(`✅ 已生成 ${OUTPUT_FILE}`);
  console.log(`   ${entries.length} 个模板已内嵌`);
}

main();